substitutions:
  device_name: amp-esp
  ip: "10.4.4.21"
  use_ip: ${ip}
  name: "Amp"
  ssid: IoTL1
  kp: 0.43552
  ki: 0.00089
  kd: 53.14351
  kp_multiplier: 0.4
  ki_multiplier: 0.4
  kd_multiplier: 0.1
  default_target_temperature: 30Â°C
  min_power: 5%
  max_power: 100%
#####################################
packages:
  common_base: !include common/base.yaml
  device_fan: !include common/esp32-fan.yaml
#####################################
